server:
  port: 8081

  servlet:
    context-path: /api/v1



spring:
  application:
    name: uzum-inventory-service
  datasource:
    password: 1111
    username: postgres
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

